hasura:
  connect-timeout: 30
  read-timeout: 30
  environments:
    MOCK:
      url: http://hasura-dev:8080
      admin-secret: your-dev-admin-secret
    SIT:
      url: http://hasura-sit:8080
      admin-secret: your-sit-admin-secret
    PROD:
      url: http://hasura-prod:8080
      admin-secret: your-prod-admin-secret